CRUD/Perpustakaan/Perpustakaan/Models/ErrorViewModel.cs
namespace Perpustakaan.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUD/Perpustakaan/Perpustakaan/Controllers/AnggotaController.cs
using Microsoft.AspNetCore.Mvc;
using Perpustakaan.datamodels;
using Perpustakaan.Services;
using Perpustakaan.viewmodels;

namespace med_id.Controllers
{
    public class AnggotaController : Controller
    {
        AnggotaService anggotaService;
        public AnggotaController(AnggotaService _anggotaService)
        {
            anggotaService = _anggotaService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            ViewBag.CurrentFilter = searchString;
            List<MAnggotum> data = await anggotaService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.Fullname.ToLower().Contains(searchString.ToLower())).ToList();
            }
            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.Fullname).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.Fullname).ToList();
                    break;
            }

            return View(data);
        }
        public IActionResult Create()
        {
            MAnggotum data = new MAnggotum();
            return PartialView(data);
        }
        [HttpPost]
        public async Task<IActionResult> Create(MAnggotum dataParam)
        {
            // dataParam.CreatedBy = 1;
            VMResponse respon = await anggotaService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<JsonResult> CheckNameIsExsist(string name, int id)
        {
            bool isExist = await anggotaService.CheckName(name, id);
            return Json(isExist);
        }

        public async Task<IActionResult> Edit(int id)
        {
            MAnggotum data = await anggotaService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MAnggotum dataParam)
        {
            //dataParam.ModifiedBy = 1;
            VMResponse respon = await anggotaService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            MAnggotum data = await anggotaService.GetDataById(id);
            return PartialView(data);
        }

        /*      [HttpGet("HapusData")]*/
        public async Task<IActionResult> Delete(int id)
        {
            MAnggotum data = await anggotaService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id, int modifedby)
        {
            //int modifedby = 1;
            VMResponse respon = await anggotaService.Delete(id, modifedby);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return RedirectToAction("Index");
        }
    }
}

CRUD/Perpustakaan/Perpustakaan/Controllers/BukuController.cs
using Microsoft.AspNetCore.Mvc;

namespace Perpustakaan.Controllers
{
    public class BukuController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CRUD/Perpustakaan/Perpustakaan/Controllers/GuruController.cs
using Microsoft.AspNetCore.Mvc;

namespace Perpustakaan.Controllers
{
    public class GuruController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CRUD/Perpustakaan/Perpustakaan/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Perpustakaan.Models;
using System.Diagnostics;

namespace MinPro334_GroupA.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CRUD/Perpustakaan/Perpustakaan/Controllers/PengurusController.cs
using Microsoft.AspNetCore.Mvc;

namespace Perpustakaan.Controllers
{
    public class PengurusController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CRUD/Perpustakaan/Perpustakaan/Views/Anggota/Create.cshtml
@using Perpustakaan.datamodels;
@model MAnggotum

<div class="card">
    <div class="card-body">


        <form asp-action="Create" method="post" id="form_input">

            <input style="width: 400px;" type="text" class="form-control" id="CreatedBy" Name="CreatedBy" oninput="check_valid()" value="1" hidden>
            <div class="mb-2 row mt-4">
                <label for="Fullname" class="col-sm-4 col-form-label">Fullname*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input style="width: 400px;" type="text" class="form-control" id="Fullname" Name="Fullname" oninput="check_valid()" value="@Model.Fullname">
                <span id="tesName" class="text-danger"></span>
            </div>
            <div class="mb-2 row mt-4">
                <label for="Kategori" class="col-sm-4 col-form-label">Kategori*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input style="width: 400px;" type="text" class="form-control" id="Kategori" Name="Kategori" oninput="check_valid()" value="@Model.Kategori">
                <span id="tesKategori" class="text-danger"></span>
            </div>
            <div class="mb-2 row mt-4">
                <label for="Username" class="col-sm-4 col-form-label">Username*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input style="width: 400px;" type="text" class="form-control" id="Username" Name="Username" oninput="check_valid()" value="@Model.Username">
                <span id="tesUsername" class="text-danger"></span>
            </div>
            <div class="mb-2 row mt-4">
                <label for="Password" class="col-sm-4 col-form-label">Password*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input style="width: 400px;" type="text" class="form-control" id="Password" Name="Password" oninput="check_valid()" value="@Model.Password">
                <span id="tesPassword" class="text-danger"></span>
            </div>
            <div class="mb-2 row mt-4">
                <label for="Email" class="col-sm-4 col-form-label">Email*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input style="width: 400px;" type="text" class="form-control" id="Email" Name="Email" oninput="check_valid()" value="@Model.Email">
                <span id="tesEmail" class="text-danger"></span>
            </div>
            <div class="mb-2 row mt-4">
                <label for="Alamat" class="col-sm-4 col-form-label">Alamat*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input style="width: 400px;" type="text" class="form-control" id="Alamat" Name="Alamat" oninput="check_valid()" value="@Model.Alamat">
                <span id="tesAlamat" class="text-danger"></span>
            </div>
            <div class="mb-2 row mt-4">
                <label for="Gender" class="col-sm-4 col-form-label">Gender*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input style="width: 400px;" type="text" class="form-control" id="Gender" Name="Gender" oninput="check_valid()" value="@Model.Gender">
                <span id="tesGender" class="text-danger"></span>
            </div>
            <div class="mb-2 row mt-4">
                <label for="Phone" class="col-sm-4 col-form-label">Phone*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input style="width: 400px;" type="text" class="form-control" id="Phone" Name="Phone" oninput="check_valid()" value="@Model.Phone">
                <span id="tesPhone" class="text-danger"></span>
            </div>
            <div class="mb-4 row col-12">
                <div class="col-6"></div>
                <div class="col-2">
                    <a class="btn btn-light" asp-controller="Anggota" asp-action="Index">Batal</a>

                </div>
                <div class="col-2">
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                </div>
            </div>

        </form>
    </div>

</div>

<script>
    function check_valid() {
        $("#tesName").text("")

    }



    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            Name: {
                required: true,
            }
        },
        messages: {
            Name: {
                required: "Nama Harus Diisi, Tidak Boleh Kosong",
            }
        },
        submitHandler: function (form) {

            var dataForm = $(form).serialize()
            var name = $("#Fullname").val()
            var id = 0

            $.ajax({
                url: "/Anggota/CheckNameIsExsist",
                type: "get", //type atau method sama aja.
                data: { name: name, id: id },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#tesName").text("Nama Sudah Ada")
                        return true;
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }

            })
        }
    })
    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Anggota/Create",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_modal").modal("hide")
                    Swal.fire({
                        icon: "success",
                        title: "Data Berhasil Ditambah",
                        showConfirmButton: false,
                        timer: 1500
                    }).then(function () {
                        window.location.reload()
                    })

                }
                else {
                    alert("Gagal Menyimpan")
                }

            }
        })
    }

</script>

CRUD/Perpustakaan/Perpustakaan/Views/Anggota/Delete.cshtml
@using Perpustakaan.datamodels;
@model MAnggotum

<div class="card">
    <div class="card-body d-flex">


        <form asp-action="SureDelete" method="post" id="form_delete">


            <input style="width: 400px;" type="text" class="form-control" id="CreatedBy" Name="CreatedBy" oninput="check_valid()" value="1" hidden>
            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id" />

            <div class="mb-4 mt-4 card-body">Anda akan menghapus Anggota <b>@Model.Fullname ?</b></div>

            <div class="row col-12">
                <div class="col-7"></div>
                <div class="col-3">
                    <a class="btn btn-outline-primary" asp-controller="Anggota" asp-action="Index">Tidak</a>

                </div>
                <div class="col-2">
                    <button type="submit" class="btn btn-primary">
                        Ya
                    </button>
                </div>
            </div>
            @*  <div >
            <a class="btn btn-outline-primary" asp-controller="Pendidikan" asp-action="Index1">Tidak</a>
            <button type="submit" class="btn btn-primary">Ya</button>
            </div> *@

        </form>

    </div>
</div>

<script>

    $("#form_delete").validate
        ({
            submitHandler: function (form) {

                var id = $("#Id").val()
                var modifedby = $("#CreatedBy").val()

                $.ajax
                    ({
                        url: '/Anggota/SureDelete',
                        type: "post",
                        data: { id: id, modifedby: modifedby },
                        dataType: "json",
                        success: function (respon) {
                            var data = respon.dataRespon

                            if (data.success) {

                                $("#my_modal").modal("hide")
                                Swal.fire({
                                    icon: "success",
                                    title: "Data Berhasil Dihapus",
                                    showConfirmButton: false,
                                    timer: 1500
                                }).then(function () {
                                    window.location.reload()
                                })
                            }
                            else {
                                alert("Gagal Menghapus")
                            }

                        }
                    })

            }

        })

</script>

CRUD/Perpustakaan/Perpustakaan/Views/Anggota/Edit.cshtml
@using Perpustakaan.datamodels;
@model MAnggotum
<div class="card">
    <div class="card-body">
        <form asp-action="Edit" method="post" id="form_input">


            <input style="width: 400px;" type="text" class="form-control" id="ModifiedBy" Name="ModifiedBy" oninput="check_valid()" value="1" hidden>
            <input type="hidden" class="form-control" id="Id" Name="Id" value="@Model.Id">

            <div class="row">
                <div class="mb-2 col-6 mt-4">
                    <label for="Name" class="col-sm-4 col-form-label">Fullname*</label>
                </div>
                <span id="validate_Name" class="text-danger"></span>
                <div class="mb-2 col-6 mt-4">
                    <label for="Kategori" class="col-sm-4 col-form-label">Kategori*</label>
                </div>
            </div>
            <div class="row">
                <div class="mb-2 col-5" style="width:410px;">
                    <input type="text" class="form-control" id="Fullname" Name="Fullname" oninput="check_valid()" value="@Model.Fullname">
                    <input type="text" class="form-control" id="NameS" Name="NameS" value="@Model.Fullname" hidden>
                </div>
                <div class="col-1"></div>
                <div class="mb-2 col-5" style="width:410px;">
                    <input type="text" class="form-control" id="Kategori" Name="Kategori" oninput="check_valid()" value="@Model.Kategori">
                </div>
            </div>
            <div class="mb-2 row mt-4">
                <label for="Username" class="col-sm-4 col-form-label">Username*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input type="text" class="form-control" id="Username" Name="Username" oninput="check_valid()" value="@Model.Username">
            </div>
            <div class="mb-2 row mt-4">
                <label for="Password" class="col-sm-4 col-form-label">Password*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input type="text" class="form-control" id="Password" Name="Password" oninput="check_valid()" value="@Model.Password">
            </div>
            <div class="mb-2 row mt-4">
                <label for="Email" class="col-sm-4 col-form-label">Email*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input type="text" class="form-control" id="Email" Name="Email" oninput="check_valid()" value="@Model.Email">
            </div>
            <div class="mb-2 row mt-4">
                <label for="Alamat" class="col-sm-4 col-form-label">Alamat*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input type="text" class="form-control" id="Alamat" Name="Alamat" oninput="check_valid()" value="@Model.Alamat">
            </div>
            <div class="mb-2 row mt-4">
                <label for="Gender" class="col-sm-4 col-form-label">Gender*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input type="text" class="form-control" id="Gender" Name="Gender" oninput="check_valid()" value="@Model.Gender">
            </div>
            <div class="mb-2 row mt-4">
                <label for="Phone" class="col-sm-4 col-form-label">Phone*</label>
            </div>
            <div class="mb-2" style="width:410px;">
                <input type="text" class="form-control" id="Phone" Name="Phone" oninput="check_valid()" value="@Model.Phone">
            </div>
            <div class="mb-4 row col-12">
                <div class="col-6"></div>
                <div class="col-2">
                    <a class="btn btn-light" asp-controller="Anggota" asp-action="Index">Batal</a>

                </div>
                <div class="col-2">
                    <button type="submit" class="btn btn-primary">
                        Simpan
                    </button>
                </div>
            </div>

        </form>
    </div>

</div>

<script>
    function check_valid() {
        $("#validate_Name").text("")

    }
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            Name: {
                required: true,
            }
        },
        messages: {
            Name: {
                required: "Nama Harus Diisi, Tidak Boleh Kosong",
            }
        },
        submitHandler: function (form) {

            var dataForm = $(form).serialize()
            var name = $("#Fullname").val()
            var nameS = $("#NameS").val()
            var id = $("#Id").val();

            $.ajax({
                url: "/Anggota/CheckNameIsExsist",
                type: "get",
                data: { name: name, id: id },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_Name").text("Nama Sudah Ada")
                        return true;
                    }
                    else {
                        Swal.fire({
                            title: "Apa Kamu Yakin ?",
                            text: "Data " + nameS + " Akan Diubah Menjadi " + name,
                            icon: "warning",
                            showCancelButton: true,
                            confirmButtonColor: "#3085d6",
                            cancelButtonColor: "#d33",
                            confirmButtonText: "Ya, Ubah Data",
                            cancelButtonText: "Batal"
                        }).then((result) => {
                            if (result.isConfirmed) {
                                // Swal.fire({
                                //     title: "Deleted!",
                                //     text: "Your file has been deleted.",
                                //     icon: "success"
                                // });
                                fungsiSubmit(dataForm)
                            }
                        });
                    }
                }

            })
        }
    })
    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Anggota/Edit",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_modal").modal("hide")
                    Swal.fire({
                        icon: "success",
                        title: "Data Berhasil Diubah",
                        showConfirmButton: false,
                        timer: 1500
                    }).then(function () {
                        window.location.reload()
                    })
                }
                else {
                    alert("Gagal Mengubah")
                }

            }
        })
    }

</script>

CRUD/Perpustakaan/Perpustakaan/Views/Anggota/Index.cshtml
@using Perpustakaan.datamodels;
@model List<MAnggotum>

<div class="card">
    <div class="card-body">

        <div class="row mb-3">
            <div class="col-12">
                <div class="mt-4 mb-4">

                    <h3 style="color:darkblue" class="align-center">
                        Jenjang Pendidikan
                    </h3>

                </div>
                <div class="d-flex justify-content-between ">
                    <button id="btn_create" class="btn btn-primary mt-10">Tambah</button>
                    <form asp-action="Index1">
                        <div class="input-group w-100">
                            <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="Search by Nama" />
                            <div class="input-group-prepend">
                                <button type="submit" class="input-group-text" title="search">
                                    <i class="bi bi-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
        <table class="table table-hover mb-3">
            <thead>
                <tr class="table-info">
                    <th class="col-3">
                        <a asp-action="Index1" asp-route-sortOrder="@ViewBag.NameSort"
                           asp-route-currentFilter="@ViewBag.currentFilter">
                            Nama
                        </a>
                    </th>
                    <th class="col-3">Phone</th>
                    <th class="col-4">Alamat</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count != 0)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Fullname</td>
                            <td>@item.Phone</td>
                            <td>@item.Alamat</td>
                            <td>
                                <a style="color:white" class="btn btn-primary btn_edit" dataid="@item.Id">
                                    Ubah
                                </a>
                                <a style="color:white" class="btn btn-danger btn_delete" dataid="@item.Id">
                                    Hapus
                                </a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>Data not found</td>
                    </tr>
                }


            </tbody>

        </table>
    </div>
</div>
<script>
    $("#btn_create").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/Anggota/Create")
        $("#my_modal").modal("show")
        $("#modal_judul").text("Tambah").css("color", "blue")
    })
    $(".btn_delete").click(function () {
        var id = $(this).attr("dataid")
        $("#modal_body").empty()
        $("#modal_body").load("/Anggota/Delete?id=" + id)
        $("#my_modal").modal("show")
        $("#modal_judul").text("Hapus!").css("color", "red")
    })
    $(".btn_edit").click(function () {
        $(".modal-dialog").addClass("modal-lg")
        var id = $(this).attr("dataid")
        $("#modal_body").empty()
        $("#modal_body").load("/Anggota/Edit?id=" + id)
        $("#my_modal").modal("show")
        $("#modal_judul").text("Edit").css("color", "blue")
    })

    $("#PageSize").val(@ViewBag.CurrentPageSize)
    $(".modal-dialog").removeClass("modal-lg")
    $("#PageSize").change(function () {
        $("#form_pagesize").submit()
    })
</script>

CRUD/Perpustakaan/Perpustakaan/Views/Buku/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

CRUD/Perpustakaan/Perpustakaan/Views/Home/Index.cshtml
<div class="row">
    <div class="col-12 col-md-4">
        <a class="card text-center" style="cursor:pointer" href="Anggota/Index">
            <div class="card-title">
                <i class="ri-team-line ri-5x"></i>
            </div>
            <div class="card-body text-center">
                <h5 class="card-title">Data Buku</h5>
            </div>
        </a>
    </div>
    <div class="col-12 col-md-4">
        <a class="card text-center" style="cursor:pointer" href="Buku/Index">
            <div class="card-title">
                <i class="ri-team-line ri-5x"></i>
            </div>
            <div class="card-body text-center">
                <h5 class="card-title">Data Buku</h5>
            </div>
        </a>
    </div>
    <div class="col-12 col-md-4">
        <a class="card text-center" style="cursor:pointer" href="Buku/Index">
            <div class="card-title">
                <i class="ri-team-line ri-5x"></i>
            </div>
            <div class="card-body text-center">
                <h5 class="card-title">Data Buku</h5>
            </div>
        </a>
    </div>
    <div class="col-12 col-md-4">
        <a class="card text-center" style="cursor:pointer" href="Buku/Index">
            <div class="card-title">
                <i class="ri-team-line ri-5x"></i>
            </div>
            <div class="card-body text-center">
                <h5 class="card-title">Data Buku</h5>
            </div>
        </a>
    </div>
</div>

CRUD/Perpustakaan/Perpustakaan/Views/Pengurus/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

CRUD/Perpustakaan/Perpustakaan/Views/Shared/_Sidebar.cshtml
@* @using Xpos334.Services;
@inject AuthService authService

@{
    int IdCustomer = Context.Session.GetInt32("IdCustomer") ?? 0;
    //string NameCustomer = Context.Session.GetString("NameCustomer") ?? "";
    int IdRole = Context.Session.GetInt32("IdRole") ?? 0;
    var menus = await authService.MenuAccess(IdRole);
}


<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->

<aside class="left-sidebar" data-sidebarbg="skin6">

    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">

                @foreach (var parent in menus)
                {
                    <li class="sidebar-item">
                        <a class="sidebar-link has-arrow" href="javascript:void(0)"
                           aria-expanded="false">
                            <i data-feather="@parent.MenuIcon" class="feather-icon"></i>
                            <span class="hide-menu">@parent.MenuName</span>
                        </a>
                        <ul aria-expanded="false" class="collapse first-level base-level-line">

                            @foreach (var child in parent.ListChild)
                            {
                                <li class="sidebar-item">
                                    <a asp-controller="@child.MenuController" asp-action="@child.MenuAction" class="sidebar-link">
                                        <span class="hide-menu">@child.MenuName</span>
                                    </a>
                                </li>
                            }

                        </ul>
                    </li>
                }

            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->



</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
 *@